//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template4435
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelData
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string UserCode { get; set; }
        public string Services { get; set; }
        public string Status { get; set; }
        public string DateofClose { get; set; }
        public string RentalTime { get; set; }
    }
}
